FROM ubuntu:22.04

ARG USERNAME=owner
ARG USER_UID=1000
ARG USER_GID=$USER_UID

# Create the user
RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
    #
    # [Optional] Add sudo support. Omit if you don't need to install software after connecting.
    && apt-get update \
    && apt-get install -y sudo \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME
	

# ********************************************************
# * Anything else you want to do like clean up goes here *
# ********************************************************

# [Optional] Set the default user. Omit if you want to keep the default as root.
USER $USERNAME
WORKDIR /home/owner

RUN sudo apt update && sudo apt install curl -y \
      && sudo apt install git -y
RUN bash -c "set -o pipefail; curl -LSs  https://raw.githubusercontent.com/pigfall/memo/master/go-install.sh | bash"
RUN bash -c "set -o pipefail; curl -LSs https://raw.githubusercontent.com/pigfall/memo/master/nvim-install.sh | bash"

RUN sudo chsh -s /bin/bash owner

CMD ["bash","-c","sleep infinity"]
